export enum RequestStatusEnum {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING_CORRECTION = 'PENDING_CORRECTION',
  CANCELLED = 'CANCELLED',
}
